name: Terraform Create AWS Infra

on:
  push:
    branches:
      - main
  #   paths:
  #     - "**/*.tf"
  #     - "envs/**"
  # workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  TF_VERSION: 1.6.6
  AWS_REGION: ap-south-1
  TF_WORKING_DIR: .

jobs:
  terraform:
    name: Terraform Apply (Prod)
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: |
          cd terraform/envs/dev
          terraform init
          terraform plan